behaviors:
  BirdAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
    network_settings:
      hidden_units: 64
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000 # 
    time_horizon: 64
    summary_freq: 10000
